// doc/react/src/common/Header.js
import React from 'react';
import styles from './header.module.css';
import DisplayUser from './DisplayUser';
import PublicSearchBar from './PublicSearchBar';
import PublicMenu from './PublicMenu';

const Header = () => {

	return (
		<div id={styles.header}>
			<span id={styles.logo}>
				<a
					tabIndex = "-1"
					href     = "/"
				>
					<img
						src = "/images/tabroom-logo.png"
						alt = "Tabroom.com by the National Speech and Debate Association"
					/>
				</a>
			</span>
			<span id={styles.rightstuff}>
				<span id={styles.profile}>
					<DisplayUser />
					<PublicSearchBar />
					<span id={styles.helpbutton} title="Tabroom Help">
						<a
							tabIndex  = "-1"
							href      = "http://docs.tabroom.com"
							target    = "_blank"
							rel       = "noopener noreferrer"
							className = "fa fa-question-circle"
						/>
					</span>
				</span>

				<PublicMenu />
			</span>
		</div>
	);
};

export default Header;

// client/src/routes/Header.svelte

	<div id="header">
		<span id="logo">
			<a
				tabindex = "-1"
				href     = "/"
			>
				<img
					src = "/images/tabroom-logo.png"
					alt = "Tabroom.com by the National Speech and Debate Association"
				>
			</a>
		</span>
	</div>

<style>

	#header {
		width     : 92%;
		margin    : auto;
		padding   : 0;
		min-width : 970px;
	}

	#logo {
		display        : inline-block;
		width          : 22%;
		margin         : 0;
		padding        : 0;
		padding-bottom : 4px;
		padding-left   : 4px;
		max-height     : 48px;
	}

	#logo a {
		margin  : 0;
		padding : 0;
	}

	#logo a img {
		max-width  : 100%;
		max-height : 100%;
	}

</style>
